apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Shared platform services (Langfuse, ClickHouse, Monitoring)
  sourceRepos:
    - https://github.com/Programmer-Network/argocd-app-of-apps.git
  destinations:
    - namespace: langfuse
      server: https://kubernetes.default.svc
    - namespace: clickhouse
      server: https://kubernetes.default.svc
    - namespace: redis
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "networking.k8s.io"
      kind: IngressClass
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: "apps"
      kind: "*"
    - group: "networking.k8s.io"
      kind: "*"
    - group: "postgresql.cnpg.io"
      kind: "*"
    - group: "secrets.hashicorp.com"
      kind: "*"
    - group: "rbac.authorization.k8s.io"
      kind: "*"
