apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-projects-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Programmer-Network/argocd-app-of-apps.git
    targetRevision: main
    path: projects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
