apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse
  namespace: clickhouse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clickhouse-role
  namespace: clickhouse
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["clickhouse-secrets"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clickhouse-rolebinding
  namespace: clickhouse
subjects:
  - kind: ServiceAccount
    name: clickhouse
    namespace: clickhouse
roleRef:
  kind: Role
  name: clickhouse-role
  apiGroup: rbac.authorization.k8s.io
