apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: clickhouse
spec:
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true
