apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ultralearning-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Ultralearning-io/infra.git
    targetRevision: main
    path: argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
